CREATE TABLE IF NOT EXISTS poke (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    cron TEXT NOT NULL,
    detail TEXT,
    sound_enabled BOOLEAN NOT NULL DEFAULT 0,
    created TIMESTAMP NOT NULL
);
