CREATE TABLE Poke (
"id" INTEGER NOT NULL PRIMARY KEY,
"name" TEXT NOT NULL UNIQUE,
cron TEXT NOT NULL,
"detail" TEXT,
created TEXT NOT NULL
) STRICT;
CREATE TABLE IF NOT EXISTS butane_migrations (
"name" TEXT NOT NULL PRIMARY KEY
) STRICT;
